OpenXT/installer

- part1/stages/Get-answerfile
There are a few issues with the NIC detection code in
network_up_for_answerfile() that will surface if:
a) you are doing a network install
b) your nics are not detected before it sets
NIC_LIST="$(find_physical_nics)"
This problem typically occurs on multi-homed systems.
This fix cleans up the logic such that we iterate
over currently known NICs, brings the interface up,
then checks for carrier signal.  If no carrier, move on
to the next known interface.  Once all interfaces have
been checked and fail carrier check, sleep for 5 seconds
and start over (redetecting for newly available interfaces).
If carrier signal is detected, use that NIC and configure it
accordingly.
OXT-287
Signed-off-by: Chris Patterson <pattersonc@ainfosec.com>
> installer: fix network interface detection

- answers/default.ans
- part1/stages/Welcome
This removes the confusing dialog asking for installation type.
The installer will now always ask for everything except what's already defined in the answer file.
The answer file now specifies only one thing: no extension pack. This is because there's currently no known extension pack. If you create one, just remove that line from your answer file (and submit a pull request if applicable).
> Remove the quick-vs-advanced dialog

- part2/stages/Find-existing-install
Accept bash globbing to describe versions from which upgrade is
supported, for that release.
OXT-380
> Upgradable version globbing

- part2/stages/Set-password
> OXT-389: use a bigger RSA certificate to match the bigger key

- part1/stages/Detect-repo
path_id no longer works from within installer, however udevadm does work to find usb devices to install from
> moved /lib/udev/path_id to /usr/bin/udevadm as former no longer exists

- part2/stages/Find-existing-install
- part2/stages/Functions/install-main
Otherwise it might require modules that are not shipped with the
installer and fail to install for that reason.
OXT-971
> lvm: only activate xenclient vgroup.

- part2/stages/Functions/install-main
Instead of doing a custome series of mounts to have more tmpfs space, use
mount_dom0 function and bump the tmpfs size used inside the function.
OXT-926
> part2: use mount_dom0 function

- part2/stages/Functions/install-main
This passes the DOM0 mount point into recovery unlock for when
upgrading from a xc scheme to the new ML scheme.
OST-955
> part2: pass dom0 mount point to recovery unlock

- part2/stages/Configure-partitions
- part2/stages/Make-XC-partition
- part2/stages/Remove-partitions
- part2/stages/Warn-disk-erasure
- part2/stages/install-main.graph
The first commit fixes a couple bugs I encountered that made the installer unable to detect and remove partitions. OpenXT was actually able to install over Windows 10 after those fixes. However, it still had no capability to remove GPT partitions, so I went ahead with the plan to always overwrite the entire 512-byte MBR area.
> OXT-1052: Warn user and always remove all partitions.

- part1/stages/Check-host-capabilities
- part2/stages/Find-existing-install
- part2/stages/Functions/install-main
- part2/stages/Make-XC-partition
- part2/stages/Remove-partitions
- Attend a minor log issue,
- Do not assume there is an OpenXT installation when failing to mount xenclient-root (or when vg xenclient exist but has not xenclient-root), it makes logs cleaner,
- Discard deprecated logic to remove partitions and/or LVM layout since the MBR is wiped prior to that.
- Attempt, as cleanly as possible, to remove the LVM layout before wiping the MBR.
> OXT-1107: Cleanup LVM layout before wiping partition table.

- part2/stages/Functions/install-main
postinstall scripts would normally create that, but the installer will
deploy images directly, so it has to be created.
See related PRs:
- https://github.com/OpenXT/xenclient-oe/pull/675
- https://github.com/OpenXT/xenclient-oe/pull/674
- https://github.com/OpenXT/installer/pull/37
> OXT-1124: part2: Create /config/etc/lvm

- part1/stages/Check-host-capabilities
- part2/stages/Find-existing-install
- part2/stages/Functions/install-main
- part2/stages/Make-XC-partition
- part2/stages/Remove-partitions
- Attend a minor log issue,
- Do not assume there is an OpenXT installation when failing to mount xenclient-root (or when vg xenclient exist but has not xenclient-root), it makes logs cleaner,
- Discard deprecated logic to remove partitions and/or LVM layout since the MBR is wiped prior to that.
- Attempt, as cleanly as possible, to remove the LVM layout before wiping the MBR.
> STABLE-7: OXT-1107: Cleanup LVM layout before wiping partition table.

- part2/stages/Functions/install-main
postinstall scripts would normally create that, but the installer will
deploy images directly, so it has to be created.
> STABLE-7: OXT-1124: part2: Create /config/etc/lvm

- part2/stages/Functions/install-main
Even with `wipe_signatures_when_zeroing_new_lvs = 1' in lvm.conf,
lvcreate will ask for confirmation to wipe the signatures from the
lv. Answer `yes' by default. Might as well pass the correct options to
make it explicit.
> OXT-1160: lvm2: lvcreate wipe signatures and zero new lv.

- part2/stages/Functions/install-main
Even with `wipe_signatures_when_zeroing_new_lvs = 1' in lvm.conf,
lvcreate will ask for confirmation to wipe the signatures from the
lv. Answer `yes' by default. Might as well pass the correct options to
make it explicit.
https://github.com/OpenXT/installer/pull/44
> STABLE-7: OXT-1160: lvm2: lvcreate wipe signatures and zero new lv.

- part2/stages/Functions/install-main
The securityfs mount is not carried through with the sysfs bind mount, so add it explicitly.
OXT-1004
> part2: add securityfs to dom0 mount

- part2/stages/Functions/install-main
The securityfs mount is not carried through with the sysfs bind mount, so add it explicitly.
OXT-1004
Signed-off-by: Daniel P. Smith dpsmith@apertussolutions.com
> [Stable-7] part2: add securityfs to dom0 mount

- common/stages/Functions/library
- part2/stages/Functions/install-main
- part2/stages/Unlock-config
With the part2 installer from OpenXT 7 being run on an OpenXT 6 dom0, some retro-compatibility has to be dealt with in the installer.
- lvm was upgraded and some new arguments were not implemented in previous versions (2.02.85 -> 2.02.105).
- the key-management and ml-measurement scripts were added with OpenXT 7, and came with changes to the installer that are not retro-compatible on an OpenXT 6 dom0 image.
> OXT-1185: OTA upgrade 6 to 7

- common/stages/Functions/library
- part2/stages/Functions/install-main
- part2/stages/Unlock-config
With the part2 installer from OpenXT 7 being run on an OpenXT 6 dom0, some retro-compatibility has to be dealt with in the installer.
- lvm was upgraded and some new arguments were not implemented in previous versions (2.02.85 -> 2.02.105).
- the key-management and ml-measurement scripts were added with OpenXT 7, and came with changes to the installer that are not retro-compatible on an OpenXT 6 dom0 image.
> STABLE-7: OXT-1185: OTA upgrade 6 to 7

- part2/stages/Functions/install-main
This PR adds support for reusing an owned TPM2.  The actual password check is implemented in https://github.com/OpenXT/xenclient-oe/pull/744.  The installer needs to re-create the TPM2 objects handles if necessary.
Depends on https://github.com/OpenXT/xenclient-oe/pull/744
OXT-1130
> OXT-1130: Reuse owned TPM2

- part2/stages/Functions/install-main
Stable-7 version.
This PR adds support for reusing an owned TPM2. The actual password check is implemented in https://github.com/OpenXT/xenclient-oe/pull/745. The installer needs to re-create the TPM2 objects handles if necessary.
Depends on https://github.com/OpenXT/xenclient-oe/pull/745
OXT-1130
> STABLE-7: OXT-1130: Reuse owned TPM2

- common/stages/Functions/library
- part2/stages/Functions/install-main
```/selinux``` does not exist. The ```selinuxfs``` is mounted in ```/sys/fs/selinux``` and should be bound to a similar path in the chroot environement. The function where this is done ```mount_dom0()``` looks a little heavy, so take the opportunity to refresh it a bit.
> OXT-1200: failed to mount SELinux sysfs in chroot env.

- part2/stages/TPM-Check
During part2/TPM-Check, using the TPM2.0 Dell firmware quirk or not for
measurment should not prompt the user, waiting for an input, to confirm
the quirk is used.
quirk_detect should not prompt the dialog box if the called script has
nothing to say.
Depends on: https://github.com/OpenXT/xenclient-oe/pull/749.
> OXT-1194: TPM-Check: Do not prompt the user empty messages.

- part2/stages/TPM-Check
During part2/TPM-Check, using the TPM2.0 Dell firmware quirk or not for
measurment should not prompt the user, waiting for an input, to confirm
the quirk is used.
quirk_detect should not prompt the dialog box if the called script has
nothing to say.
Depends on: https://github.com/OpenXT/xenclient-oe/pull/750.
> STABLE-7: OXT-1194: TPM-Check: Do not prompt the user empty messages.

- part2/stages/Find-existing-install
- part2/stages/Functions/install-main
- Installer has `udev` running, so rely on it for mapper nodes;
- Work-around what seems to be a race between `eudev` and LVM.
See https://github.com/OpenXT/xenclient-oe/pull/830
> OXT-880: OE upgrade to pyro

- common/stages/Functions/library
- part1/stages/Status-report
- part2/stages/Remove-partitions
This was initially part of https://github.com/OpenXT/installer/pull/65 and got lost during rebase.
Fix installation on NVMe drives by handling devfs symlink naming conventions in the `Remove-partitions` stage. Introduce `reread_partition_table` to handle LVM `vgchange -a -n`.
> OXT-1286: LVM Physical Volume an Volume Group removal

- part2/stages/Functions/install-main
Signed-off-by: Richard Turner <turnerr@ainfosec.com>
Without the udev settling, follow-on lvcreate calls will sometimes error with "Aborting. Failed to activate new LV to wipe the start of it." This problem can occur randomly during initial provisioning after multiple lvcreate calls, such as in the mk_xc_lvm function. This problem is completely dependent on how udev responds. This change proposes waiting until all of the udev events are cleared before creating another logical volume.
> Allow udev to settle after the lvcreate

- part2/stages/Make-XC-partition
Fixes the issue of UEFI drives not being recognized by some BIOS's
> Only set the MBR's active boot flag if in legacy mode

- part2/stages/TPM-Check
tpm_is_owner_wks checks if the TPM owner is the well-known secret.  It
does this by authenticating to the TPM.  If the TPM is already owned,
this adds another failure to the TPM.  Too many failures and you'll hit
the TPM's timeout.
Since we don't actually do anything with the result of tpm_is_owner_wks,
just remove the test.
OXT-1308
> OXT-1308: TPM-Check: Remove well known secret owner check

- part2/stages/TPM-Check
This is the Stable-8 version of https://github.com/OpenXT/installer/pull/70
tpm_is_owner_wks checks if the TPM owner is the well-known secret.  It
does this by authenticating to the TPM.  If the TPM is already owned,
this adds another failure to the TPM.  Too many failures and you'll hit
the TPM's timeout.
Since we don't actually do anything with the result of tpm_is_owner_wks,
just remove the test.
OXT-1308
(cherry picked from commit b157245f44192402fb65f05f495b65bd4a0d1757)
> STABLE-8: OXT-1308: TPM-Check: Remove well known secret owner check

- part2/stages/Functions/install-main
There seems to be a delay after lvrename completed before udev creates
the new block device node.  Sometimes the installer fails because it
tries to mount $ROOT_DEV before the device node is present.  Loop for a
maximum of 10 seconds to give time for it to appear.
A simple sleep 1 seems sufficient in testing, but that is fragile.
OXT-1298
I'm not super thrilled with this approach, but this failure bit me a bunch today.  Re-running installations got old fast.
> OXT-1298: install-main: Wait on ROOT_DEV appearance

- part1/stages/Initialise-state
Silence warning:
modprobe: FATAL: Module fbcon not found in directory /lib/modules/4.14.34
Complements https://github.com/OpenXT/xenclient-oe/pull/901
> OXT-1321: fbcon: The module is now builtin.

- part1/stages/Initialise-state
Silence warning:
modprobe: FATAL: Module fbcon not found in directory /lib/modules/4.14.34
(cherry picked from commit d73307e54d6e7c2ffea7e4780908416251da7506)
Relates to: https://github.com/OpenXT/xenclient-oe/pull/904
> STABLE-8: OXT-1321: The module is now builtin.

- part2/stages/Functions/install-main
This is the Stable-8 version of https://github.com/OpenXT/installer/pull/73
There seems to be a delay between lvrename completing and udev creating
the new block device node.  Sometimes the installer fails because it
tries to mount $ROOT_DEV before the device node is present.  Use udevadm
settle to wait on any pending udev changes.
OXT-1298
(cherry picked from commit cf09fcf979b17abd229272d7dfe2a523764a222e)
> STABLE-8: OXT-1298: install-main: Wait on ROOT_DEV appearance

- part2/stages/Make-XC-partition
Fixes the issue of UEFI drives not being recognized by some BIOS's
Stable-8 version of original PR: https://github.com/OpenXT/installer/pull/69
(cherry picked from commit 44f67b535f68aad56b538917e70fa1854d44da3e)
> STABLE-8: Only set the MBR's active boot flag if in legacy mode

- part2/stages/Configure-partitions
Commit 86242803de16d5341b76c222f2e8ba785c48ce76 removed coalescing of
erase-entire-disk in partition_mode_is_unique.  Without this,
Configure-partitions presents an extra prompt in interactive mode for a
legacy boot between use-free-space and erase-entire-disk.  This is not
seen for UEFI boots since that provides an answerfile specifying
partition-mode erase-entire-disk bypassing the prompt even in
interactive mode.
Restore the coalescing to bypass the superfluous prompt.
This reverts part of 86242803de16d5341b76c222f2e8ba785c48ce76
OXT-1349
> OXT-1349: Configure-partitions: Restore erase-entire-disk folding

- part2/stages/Functions/install-main
It's surprising to see "Taking ownership of TPM" during a non-measured
launch install.  Move those messages inside the conditional block so
they are only printed when appropriate.
OXT-1357
> OXT-1357: Restrict TPM messages to measured launch

- part2/stages/Functions/install-main
It's surprising to see "Taking ownership of TPM" during a non-measured
launch install.  Move those messages inside the conditional block so
they are only printed when appropriate.
OXT-1357
(cherry picked from commit 5fd306094d3c6fc5cf9d9f862fdfefe32f6e5aed)
Stable-8 version of https://github.com/OpenXT/installer/pull/82
> STABLE-8: OXT-1357: Restrict TPM messages to measured launch

- part2/stages/Functions/install-main
If we are upgrading, we must write out /config/config.pcrs to ensure new
values in case the PCR selection changed.
OXT-1351
Depends on https://github.com/OpenXT/xenclient-oe/pull/925
> OXT-1351: Change PCR Sealing selection on upgrade

- part2/stages/Functions/install-main
This is the stable-8 version of https://github.com/OpenXT/installer/pull/80
If we are upgrading, we must write out /config/config.pcrs to ensure new
values in case the PCR selection changed.
OXT-1351
(cherry picked from commit e863a010aaf620734c1c308854104881e3314082)
Depends on https://github.com/OpenXT/xenclient-oe/pull/934
> STABLE-8: OXT-1351: Change PCR Sealing selection on upgrade

- part2/stages/Functions/install-main
OXT-1344
Manually running the installer for upgrade fails in create_efi_boot_entries running efibootmgr because TARGET_DISK is unset.  We really want the ESP partition, and we already have the in the calling function, copy_to_esp, so pass it in.
OXT-1328
Add remove_efi_boot_entries to remove already existing OpenXT bootloader entries.  Otherwise duplicate entries are created each time OpenXT is re-installed over itself.  The existing call to `efibootmgr -D` removes duplicates from the BootOrder Variable - not duplicate entries.
> UEFI Fixes

- part2/stages/Functions/install-main
This is the stable-8 version of https://github.com/OpenXT/installer/pull/78
OXT-1344
Manually running the installer for upgrade fails in create_efi_boot_entries running efibootmgr because TARGET_DISK is unset. We really want the ESP partition, and we already have that in the calling function, copy_to_esp, so pass it in.
OXT-1328
Add remove_efi_boot_entries to remove already existing OpenXT bootloader entries. Otherwise duplicate entries are created each time OpenXT is re-installed over itself. The existing call to efibootmgr -D removes duplicates from the BootOrder Variable - not duplicate entries.
> STABLE-8: UEFI Fixes

- part2/stages/Configure-partitions
This is the stable-8 version of https://github.com/OpenXT/installer/pull/81
Commit 86242803de16d5341b76c222f2e8ba785c48ce76 removed coalescing of
erase-entire-disk in partition_mode_is_unique.  Without this,
Configure-partitions presents an extra prompt in interactive mode for a
legacy boot between use-free-space and erase-entire-disk.  This is not
seen for UEFI boots since that provides an answerfile specifying
partition-mode erase-entire-disk bypassing the prompt even in
interactive mode.
Restore the coalescing to bypass the superfluous prompt.
This reverts part of 86242803de16d5341b76c222f2e8ba785c48ce76
OXT-1349
(cherry picked from commit 0e686df4d2a9c5711dde3533151bf0d1b815c0dc)
> STABLE-8: OXT-1349: Configure-partitions: Restore erase-entire-disk folding

- common/stages/Functions/fetch
When chaining network boot to a different server, `/etc/dhcp-prefix` will not be relevant to the new TFTP server used to fetch files.
> tftp: answer files from a non-default tftp server.

- common/stages/Functions/fetch
This configuration could happen when chaining network boot to a
different server. /etc/dhcp-prefix in this case will not be relevant to
the new given tftp server.
In general it seems using /etc/dhcp-prefix is relevant when accessing
the tftp server given by the DHCP server (option 210?). This is obvious
when accessing tftp://dhcp/<path>.
(cherry picked from commit a25f6ab2cbd0e6936a4a85ab08b085282688a961)
> STABLE-8: installer: tftp server may not be dhcp default.

- part2/stages/Functions/install-main
The initramfs.gz is too large for the old 32M sized tmpfs,
as hash_module must first extract the compressed .gz. Also
some bind mounts were left hanging after upgrade completed,
make sure we umount them in the proper order.
Signed-off-by: Chris <rogersc@ainfosec.com>
> [upgrade] Increase tpmfs size and unmount all fs

- part2/stages/Functions/install-main
The initramfs.gz is too large for the old 32M sized tmpfs,
as hash_module must first extract the compressed .gz. Also
some bind mounts were left hanging after upgrade completed,
make sure we umount them in the proper order.
Signed-off-by: Chris <rogersc@ainfosec.com>
(cherry picked from commit fe3ca1bf256b988dab01972d1b77d8d6bbd94db1)
> STABLE-8: [upgrade] Increase tpmfs size and unmount all fs

- common/stages/Functions/library
- part2/stages/Functions/install-main
Add two functions to the common script library to parse devnodes disk
and partition and use them with efibootmgr when writting efi boot
entries for a new OpenXT installation.
> OXT-1372: installer: Amend disk/partition for efibootmgr

- common/stages/Functions/library
- part2/stages/Functions/install-main
Add two functions to the common script library to parse devnodes disk
and partition and use them with efibootmgr when writting efi boot
entries for a new OpenXT installation.
(cherry picked from commit 864c5077675a725861a5633e0bd28bf31c24db35)
Master PR: https://github.com/OpenXT/installer/pull/92
> STABLE-8: OXT-1372: installer: Amend disk/partition for efibootmgr

- part2/stages/Functions/install-main
Dom0 doesn't ship with the efibootmgr binary. If we're
upgrading, just leave the boot entries as is.
OXT-1376
> OXT-1376: installer: Don't create new boot entries on upgrade

- part2/stages/Functions/install-main
Dom0 doesn't ship with the efibootmgr binary. If we're
upgrading, just leave the boot entries as is.
OXT-1376
> STABLE-8: OXT-1376: installer: Don't create new boot entries on upgrade

- part2/stages/Functions/install-main
- part2/stages/TPM-Check
Supporting installer changes for [#1062]( https://github.com/OpenXT/xenclient-oe/pull/1062)
[OXT-1456](https://openxt.atlassian.net/browse/OXT-1456)
> [tpm2-tools] Uprev from v2.0.0 to v3.1.3

- part2/stages/Commit-preserved-data
- part2/stages/Functions/file-paths
- part2/stages/Functions/install-main
to support forward sealing when upgrading from a 32-bit version
of OpenXT.
OXT-1539
Signed-off-by: Chris <rogersc@ainfosec.com>
> STABLE-9: [upgrade] Use the upgrade-compat image

- part2/stages/Functions/install-main
We can't easily gunzip and install a random file like a compressed
servicevm disk image.  Add support for "gz" PACKAGE_TYPE to file.  This
way a compressed file can be extracted and installed directly from the
installer.
add to the manifest file:
file gz required servicevm.vhd.gz /storage/disks/servicevm.vhd
> part2: Add support for gunzip-ing files

- part2/stages/Functions/install-main
We can't easily gunzip and install a random file like a compressed
servicevm disk image.  Add support for "gz" PACKAGE_TYPE to file.  This
way a compressed file can be extracted and installed directly from the
installer.
add to the manifest file:
file gz required servicevm.vhd.gz /storage/disks/servicevm.vhd
(cherry picked from commit 5423a2cb29d5bec181cffa09679666046c814a55)
> STABLE-9: part2: Add support for gunzip-ing files

- part2/stages/Functions/install-main
The compat codepaths were missing some error checking which this PR adds.  
`mount_upgrade_compat` wasn't exiting on failure, so execution continued.  Return an error for that case.
mount_upgrade_compat can fail if it wasn't written into a logical volume.  We need create_lv to return an error when it cannot create an LV.
While touching the seal_system, prefix the seal commands with `do_cmd` so they are logged.
NOTE: Regardless of this PR, we don't abort the installer on forward sealing failure.  This means we'll reboot and fail the measured launch.  At the time seal_system is called, all the files have been updated, so there isn't a way to fail gracefully.
"install-main: Return failure from create_lv " is a cherry pick from the master PR.
"install-main: Add do_cmd to seal_system" is a …
> STABLE-9: compat error checking additions

- part2/stages/Functions/install-main
There are non-compat error checking additions from https://github.com/OpenXT/installer/pull/103
We need create_lv to return an error when it cannot create an LV.
While touching the seal_system, prefix the seal commands with do_cmd so they are logged.
> Error checking additions

- part2/stages/Functions/install-main
We need to chroot into the new root filesystem so that we write the new
pcr configuration and not the existing one.  Without this, we won't pick
up a new PCR configuration during an upgrade.
OXT-1351
> OXT-1351: seal-system: Run write_config_pcrs from chroot

- part1/stages/Check-GPU
Add a check to the host capabilities section that tests whether the
onboard VGA device is the boot VGA device. If not the user is served with
a warning. User can continue installation if desired, they are instructed
to change primary display after the install succeeds in such an event.
Related to OXT-1600
Signed-off-by: Tyler McGavran <mcgavrant@ainfosec.com>
> [master] Add boot VGA device warning

- part1/stages/Check-GPU
Add a check to the host capabilities section that tests whether the
onboard VGA device is the boot VGA device. If not the user is served with
a warning. User can continue installation if desired, they are instructed
to change primary display after the install succeeds in such an event.
Related to OXT-1600
Signed-off-by: Tyler McGavran <mcgavrant@ainfosec.com>
> [stable-9] Add boot VGA device warning

- part2/stages/Functions/install-main
This is the stable-9 version of https://github.com/OpenXT/installer/pull/106
We need to chroot into the new root filesystem so that we write the new
pcr configuration and not the existing one.  Without this, we won't pick
up a new PCR configuration during an upgrade.
OXT-1351
(cherry picked from commit f55a626f4498b8458dd98e69061d1d5528e1a902)
[stable-9: Run out of compat-upgrade if necessary]
> S9: OXT-1351: seal-system: Run write_config_pcrs from chroot

- part2/stages/Functions/install-main
@dpsmith tagging for visibility
OXT-1632
> [copy_to_esp] Limit search to target disk only

- common/stages/Functions/library
- part2/stages/Remove-partitions
udev may create a symlink alias to the block device in /dev for some NVMe drives. `get_devnode_{disk,partition}` assumes (per comment) they are passed the block device
path, but some utility tools (e.g, lvm-utils) can return the symlink alias instead that end up being passed as argument.
Add a sanitizing function to avoid that.
part2 already has snippets doing just that when trying to remove any existing LVM setup cleaning. So use the new function instead.
> OXT-1654: Handle NVMe symlinks in /dev.

- common/stages/Functions/library
- part2/stages/Remove-partitions
udev may create a symlink alias to the block device in /dev for some NVMe drives. `get_devnode_{disk,partition}` assumes (per comment) they are passed the block device
path, but some utility tools (e.g, lvm-utils) can return the symlink alias instead that end up being passed as argument.
Add a sanitizing function to avoid that.
part2 already has snippets doing just that when trying to remove any existing LVM setup cleaning. So use the new function instead.
> S9: OXT-1654: Handle NVMe symlinks in /dev.

- part2/stages/Functions/install-main
OpenEmbedded classes and recipes follow the convention that an image's
init image is called initrd when built into the image. In order to
better use OpenEmbedded's existing tooling it is helpful to follow then
naming convention of the init image.
This is tied to OpenXT/xenclient-oe#1221
> part2: renaming initramfs.gz to initrd

- part2/stages/Functions/install-main
This commit replaces the custom OXT `falloc` command script
with the standard `fallocate` call that gets pulled in by `util-linux`.
Signed-off-by: Tim Konick <konickt@ainfosec.com>
> [OXT-1640] Remove legacy `falloc` script

- part2/stages/Functions/install-main
- part2/stages/Remove-partitions
Doing so removes the handle from the device-mapper on the block device.
lvm-utils will fail to use the blockdev otherwise, e.g:
```
Can't open /dev/nvme0n1p3 exclusively.  Mounted filesystem?
Can't open /dev/nvme0n1p3 exclusively.  Mounted filesystem?
```
> OXT-1701: part2: Deactivate VGs before LV manipulation.

- part1/stages/Choose-install-type
- part1/stages/Functions/install-main
- part1/stages/Functions/optical-media
- There is a spurious error when trying to detect if the platform has a cdrom drive, silence it.
- Fix bash `test` operators misuses in `install-main` when unpacking the part2 (control) tarball, amend the other operators while at it
- Add some informations to diagnose issues that may arise with the part2 (control) tarball.
> part1: Attend minor glitches in media detection and repository unpacking
