part2/stages/Functions/install-main

Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

Dynamically create dom0 rootfs lv size.

---

part2/stages/Functions/install-main

OXT-389: implement recommended changes

---

part1/stages/Check-GPU

Just show a warning when no Intel GPU is found

---

part2/stages/Make-XC-partition

Fix sfdisk usage

---

common/stages/Functions/library
part2/stages/Configure-partitions
part2/stages/Functions/install-main
part2/stages/Make-XC-partition
part2/stages/Select-hard-disk

Fix partition handling for NVMe support

---

part2/stages/Select-hard-disk

non-interactive-mode: default to first hard drive

---

part2/stages/Initialise-state
part2/stages/TPM-Check

Start TrouSerS earlier

---

part2/stages/Warn-disk-erasure

Signed-off-by: Christopher Clark <christopher.clark6@baesystems.com>

OXT-690: make interactive default "no" for destructive installs

---

answers/auto-cd.ans
answers/auto-hard-disk.ans
answers/cd-only.ans
answers/default.ans
answers/hard-disk-only.ans
answers/iscsi.ans
answers/network.ans
answers/usb.ans

answer files: allow dev repo certs

---

answers/auto-cd.ans
answers/auto-hard-disk.ans
answers/cd-only.ans
answers/default.ans
answers/hard-disk-only.ans
answers/iscsi.ans
answers/network.ans
answers/usb.ans

OXT-744
(cherry picked from commit d0af70e33141c94f36cf1e512817695d2ffd7812)

STABLE-6: answer files: allow dev repo certs

---

answers/auto-cd.ans
answers/auto-hard-disk.ans
answers/cd-only.ans
answers/default.ans
answers/hard-disk-only.ans
answers/iscsi.ans
answers/network.ans
answers/usb.ans

OXT-744
(cherry picked from commit d0af70e33141c94f36cf1e512817695d2ffd7812)

STABLE-5: answer files: allow dev repo certs

---

answers/auto-cd.ans
answers/auto-hard-disk.ans
answers/cd-only.ans
answers/default.ans
answers/hard-disk-only.ans
answers/iscsi.ans
answers/network.ans
answers/usb.ans

OXT-744
(cherry picked from commit d0af70e33141c94f36cf1e512817695d2ffd7812)

STABLE-4: answer files: allow dev repo certs

---

part1/stages/Check-host-capabilities

OXT-586
Signed-off-by: Ross Philipson <philipsonr@ainfosec.com>

[install] Use xenops to test for VTx/VTd.

---

part1/stages/Check-host-capabilities

Switch from xenops to xl to get hardware information

---

answers/doc/answerfiles.txt
part1/stages/Status-report
part2/stages/Commit-main
part2/stages/Commit-preserved-data
part2/stages/Functions/file-paths
part2/stages/Functions/install-main
part2/stages/Install-fresh
part2/stages/Seal-upgrade
part2/stages/Set-password
part2/stages/TPM-Check
part2/stages/commit-main.graph

This changeset makes the necessary changes to the installer to support the re-architecturing of the Measured Launch process.
OXT-536

Adapt installer for new Measured Launch

---

part2/stages/Configure-partitions
part2/stages/Make-XC-partition
part2/stages/Remove-partitions
part2/stages/Warn-disk-erasure
part2/stages/install-main.graph

STABLE-7: OXT-1052: Warn user and always remove all partitions.

---

part2/stages/Functions/install-main
part2/stages/TPM-Check

OXT-938
Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

STABLE-7: [tpm2.0] Add tpm2 support in installer

---

part2/stages/Functions/install-main
part2/stages/TPM-Check

OXT-938
Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

[tpm2.0] Add tpm2 support in installer

---

part2/stages/install-main.graph

OXT-1052
Signed-off-by: Troy Crosley <crosleyt@ainfosec.com>

Delay wiping MBR until after Ready-to-install.

---

part2/stages/install-main.graph

STABLE-7: Delay wiping MBR until after Ready-to-install.

---

part2/stages/Functions/install-main

Increase LUKS iterations

---

part2/stages/Functions/install-main

STABLE-7: Increase LUKS iterations

---

part1/stages/Configure-network-repo
part1/stages/Download-install-files

OXT-1248: Add https support

---

part1/stages/Configure-network-repo
part1/stages/Download-install-files

OXT-1248
(cherry picked from commit a7081388415b8a65fdad617794bc655c4ef2d828)

STABLE-7: OXT-1248: Add https support

---

part2/stages/Functions/install-main

OXT-1221
Signed-off-by: mahantesh <mahantesh@durandal.securext.net>

blktap3: update environment variable name

---

part2/stages/Commit-preserved-data

Signed-off-by: Richard Turner <turnerr@ainfosec.com>

[Linux 4.14] Fix SELinux labeling in /boot/system/config

---

part2/stages/Make-XC-partition

Run parted in script mode and explain dd output

---

part2/stages/Make-XC-partition

(cherry picked from commit 01a07418f2d4f09a7ff4bb40987e05c0558a4c5f)

STABLE-8: Run parted in script mode and explain dd output

---

part2/stages/Functions/install-main

Signed-off-by: Tamas K Lengyel <lengyelt@ainfosec.com>

OXT-1318: Install tboot and sinit modules to ESP

---

part2/stages/Functions/install-main

Clear outdated files from ESP during upgrades

---

part2/stages/Commit-preserved-data
part2/stages/Functions/install-main
part2/stages/Install-fresh
part2/stages/Install-upgrade

OXT-1549
Signed-off-by: Chris <rogersc@ainfosec.com>

STABLE-9: OXT-1549: [installer] Only install upgradecompat on upgrades

---

part2/stages/Functions/install-main

S9: [copy_to_esp] Limit search to target disk only

---

part2/stages/Functions/install-main

An update to the recommended minimum parameters for encrypted file systems

part2: update dm-crypt parameters
